# Generated by Django 4.2.7 on 2023-11-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('year', models.DateField()),
            ],
        ),
    ]
