# Generated by Django 4.2.7 on 2023-11-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='album', name='year'),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(),
            preserve_default=False
        ),
    ]
